init python:
    # Cпиcок женских имен
    female_names = [
        "Abequ", "Abey", "Adoette", "Alameda", "Alaqua", "Aleshanee", "Amadahy", "Amitola", "Anaba", "Anna", "Awanatu", "Awenasa", "Ayita",
        "Catori", "Chapawee", "Chenoa", "Chitsa", "Chosovi", "Cocheta",
        "Dena", "Dowanhowee",
        "Enola", "Etenia",
        "Haloke", "Halona", "Hateya", "Helki", "Honovi",
        "Kachina", "Kai", "Kaliska", "Kanti", "Kasa", "Kay", "Kewanee", "Kimi", "Kolaki", "Kwanita",
        "Lenmana", "Leotie", "Litonya", "Lomahongva",
        "Mai", "Makawee", "Malia", "Mansi", "Mapiya", "Meda", "Miakoda", "Mitena", "Muna",
        "Nahimana", "Nara", "Nashota", "Nata", "Ninovan", "Nittawosew", "Nituna", "Nova", "Numees", "Nuna", "Nuttah",
        "Odina", "Olathe", "Omusa", "Onawa", "Orenda",
        "Pamuy", "Pauwau", "Pavati", "Petah", "Poloma", "Powaqa",
        "Quanah",
        "Rozene",
        "Salali", "Sapata", "Shada", "Shuman", "Sinopa", "Sitala", "Snana", "Sokanon", "Sonoma", "Suleta", "Suni", "Sunki",
        "Tadewi", "Tahki", "Taima", "Taipa", "Takala", "Talulah", "Tansy", "Tiva", "Tuwa",
        "Una", "Urika", "Utina",
        "Wachiwi", "Waneta", "Wapun", "Wenona", "Wichahpi", "Wikimak", "Winema", "Winona",
        "Yenene", "Yona",
        "Zaltana", "Zitkala" ]
    # Список мужских имен
    male_names = [
        "Adahy", "Ahanu", "Ahiga", "Ahmik", "Akando", "Anoki", "Apiatan", "Avonaco", "Awan",
        "Bilagaana",
        "Chatan", "Chayton", "Chesmu", "Cheveyo", "Chogan", "Ciqala", "Cochise",
        "Delsin", "Dohate", "Dohosan",
        "Elan", "Elki", "Enyeto", "Etu",
        "Gosheven",
        "Hahnee", "Hakan", "Halian", "Hanska", "Hassun", "Helaku", "Helki", "Hesutu", "Hinto", "Holata", "Honiahaka", "Honon", "Hotah", "Howahkan",
        "Illanipi", "Inteus", "Istaqa",
        "Jolon",
        "Kanuna", "Kele", "Kestejoo", "Kitchi", "Knoton", "Kohana", "Kosumi", "Kotori","Kuruk",
        "Lokni", "Lonato", "Lootah",
        "Machakw", "Mahkah", "Mahpee", "Matoskah", "Mikasi", "Mingan", "Mohe", "Muata", "Muraco",
        "Nahiossi",
        "Nakai", "Nashashuk", "Nashoba", "Nastas", "Nigan", "Niyol", "Nodin", "Nootau", "Notaku",
        "Ohanko", "Ohanzee", "Onacona", "Osceola", "Otaktay", "Ouray",
        "Patamon", "Payatt", "Pimne",
        "Qochata", "Quanah",
        "Sahale", "Samoset", "Satanta", "Sewati", "Shilah", "Sipatu", "Skah", "Songaa",
        "Tahkeome","Takoda", "Tashunka", "Tasunke", "Teluhci", "Telutci", "Tokala", "Tooantuh", "Tuari", "Tupi",
        "Vohkinne",
        "Wahkan", "Wanahton", "Wapi", "Wicasa",
        "Yanisin", "Yuma" ]
